### ISSUE TITLE
dataviews aren’t dimmed

### ISSUE THREAD

**Issue by ces3001** [michaellee/stille#13]
Love Stille. Thank you.
However, I’ve noticed the output of `dataview` and `dataviewjs` within the three-back-tick code elements aren’t dimmed. Can you help adding those elements so that they too are dimmed?

Thanks!

**Comment by michaellee** [comment]
@ces3001 thanks for the Stille, love!

Let me look into this.

**Comment by michaellee** [comment]
Hey @ces3001 

I looked into this and not sure about a solution going forward. I could likely dim out the output of dataview, but while Stille is on, it is unlikely, you can focus and undim it. This is because Obsidian will always put focus on the raw element and not the embedded element that Dataview outputs.

If this is what you had in mind, let me know and I can give it a shot.

**Comment by michaellee** [comment]
Hey @ces3001 thanks again for bringing this to my attention. I've since updated Stille so that it dims dataviews. You can update to the latest version `1.3.0` and it should dim it now.
