### ISSUE TITLE
File/heading/block embeds are not dimmed

### ISSUE THREAD

**Issue by zanesterling** [michaellee/stille#14]
Hi, I love Stille! It helps me stay on task by only hilighting what I'm working on.

I also like using the `![[File Name#header#...]]` syntax to embed blocks and headers from other files. That way I can have a comprehensive daily journal, but still have different things I did that day filed away in their separate projects for future reference.

Unfortunately they don't seem to play well together. Stille doesn't dim these embeds.

Is it possible to get Stille to dim embeded file/heading/block links?

Thanks!

**Comment by michaellee** [comment]
Hey @zanesterling thanks for the Stille, love!

I think I can achieve this.

If I can, I'll let you know once the update is live.

**Comment by michaellee** [comment]
Hey @zanesterling  

I looked into this and not sure if I've got a decent solution moving forward. The reason being embedded blocks can't be highlighted (focused on) so I could never undim them.

If the intent is to just dim them with the understanding that Stille will have to be turned off in order to see the embedded block undimmed, I could work on a solution.

Let me know.

**Comment by zanesterling** [comment]
Dimming them as long as Stille as on seems totally reasonable to me. If doc
A has doc B embedded, I don’t edit doc B from doc A, so I don’t ever need
to read it while Stille is on.

Thanks for looking into it!

Michael Lee ***@***.***> schrieb am Mi. 7. Sept. 2022 um
16:07:

**Comment by michaellee** [comment]
@zanesterling I've just pushed up v1.3.0 could you update and give it a run.

I've made it so that both dataview embeds and native Obsidian embeds are now dimmed as well.

Thanks for the feedback!

**Comment by zanesterling** [comment]
The fix works great! Thanks so much for the quick update ❤️
